name: amap_search_fluttify
description: An `Amap` Search Component, Powered By `Fluttify` Engine, A Dart Bindings Generator for Native SDK.
version: 0.7.8+dbad1c3
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_search_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.5.6+3ebdbdc
  foundation_fluttify: ^0.4.14+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_search_fluttify
        pluginClass: AmapSearchFluttifyPlugin
      ios:
        pluginClass: AmapSearchFluttifyPlugin