name: amap_search_fluttify
description: An `Amap` Search Component, Powered By `Fluttify` Engine, A Dart Bindings Generator for Native SDK.
version: 0.17.0-dev.0
authors:
  - yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_search_fluttify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.15.0-dev.0
  
  foundation_fluttify: ^0.12.0-dev.0
  core_location_fluttify: ^0.7.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_search_fluttify
        pluginClass: AmapSearchFluttifyPlugin
      ios:
        pluginClass: AmapSearchFluttifyPlugin