name: amap_search_fluttify
description: An `Amap Search` Map Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.18.0-rc.0
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify: ^0.13.0-rc.0
  core_location_fluttify: ^0.7.0-rc.0
  amap_core_fluttify: ^0.17.0-rc.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_search_fluttify
        pluginClass: AmapSearchFluttifyPlugin
      ios:
        pluginClass: AmapSearchFluttifyPlugin